Improve perfomance
yiisoft/rbac-php pull request #63
Opened 2023-09-06 07:28 UTC by arogachev

| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ❌
| Breaks BC?    | ✔️

Related: https://github.com/yiisoft/rbac/pull/170.

2023-09-25 07:08 UTC, vjik requested changes

2023-09-26 02:25 UTC, Tigrov commented on src/ItemsStorage.php
> +                $parent = $this->get($parentName);
It will be called once due to `brake;` below. And may not be called due to `continue;` above.

2023-09-27 04:19 UTC, arogachev commented on composer.json
> +        "yiisoft/rbac": "dev-165-improve-perfomance",
#68

2023-09-27 04:25 UTC, arogachev commented on src/ItemsStorage.php
> +        );
This exceeds line's max length (120 chars).

2023-09-27 04:31 UTC, arogachev commented on src/ItemsStorage.php
> +                $parent = $this->get($parentName);
Tests will fail then.

2023-09-27 04:40 UTC, arogachev commented on src/ItemsStorage.php
> +        return $this->hasLoop($childName, $parentName);
`hasChild()` is for checking child's existence at any level (recursive). Non-recursive variation is in separate method `hasDirectChild()`.

2023-09-27 05:31 UTC, arogachev commented on src/ItemsStorage.php
> +        return $this->hasLoop($childName, $parentName);
I refactored this method to be more clear.

2023-09-27 05:32 UTC, arogachev commented
The changes have been synced with main branch.

2023-09-27 07:01 UTC, vjik commented on src/ItemsStorage.php
> +        );
> This exceeds line's max length (120 chars).

Convert short fn to full form.

2023-09-27 07:01 UTC, vjik approved these changes

2023-09-27 07:19 UTC, merged